---
# leaf 1
RID: 1.1.1.1
Loopback0: 10.0.0.11
interfaces:
  - name: "1/1"    
    description: "SPINE-1"    
    ip: 10.1.1.2/30    
  - name: "1/2"    
    description: "SPINE-2"    
    ip: 10.2.1.2/30
vlans_local:
  - 10

edge_interfaces:
  1/3:
    description: "Downlink to PC"
    port_type: "edge"
    mode: "access"
    access_vlan: 10
    spanning_tree: "edge"
    bpduguard: "enable"

  1/4:
    description: "ESXi Host"
    port_type: "edge"
    mode: "trunk"
    trunk_allowed: "10,20"
    spanning_tree: "trunk"

  1/5:
    description: "ESXi Host"
    port_type: "edge"
    mode: "trunk"
    trunk_allowed: "10,20"
    native_vlan: "20"
    spanning_tree: "trunk"

